name: CI
on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Dependency
        run: make setup

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
